import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { mkdirSync, writeFileSync } from 'node:fs'

const require = createRequire(import.meta.url)
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sdkRoots = [
  process.env.DEVECO_SDK_HOME,
  process.env.HARMONY_SDK_HOME,
  '/Applications/DevEco-Studio.app/Contents/sdk',
].filter((value) => typeof value === 'string' && value.length > 0)

let resourceTablePath = ''
let symbols = null
for (const sdkRoot of sdkRoots) {
  const candidate = join(
    sdkRoot,
    'default/openharmony/ets/build-tools/ets-loader/sysResource.js',
  )
  try {
    const table = require(candidate)
    if (table && table.sys && table.sys.symbol) {
      resourceTablePath = candidate
      symbols = table.sys.symbol
      break
    }
  } catch (_error) {}
}

if (symbols === null) {
  throw new Error(
    'Unable to locate sysResource.js. Set DEVECO_SDK_HOME to the DevEco Studio SDK root.',
  )
}

const names = Object.keys(symbols).sort((left, right) => left.localeCompare(right))
const sourceLabel = resourceTablePath.substring(resourceTablePath.indexOf('default/'))
const lines = [
  '// Generated by scripts/generate_system_symbol_catalog.mjs.',
  `// Source: ${sourceLabel}`,
  `// System symbols: ${names.length}`,
  '// Re-run the generator after changing the compile SDK; do not edit this file by hand.',
  '',
  'export class SystemSymbolEntry {',
  '  name: string',
  '  symbol: Resource',
  '',
  '  constructor(name: string, symbol: Resource) {',
  '    this.name = name',
  '    this.symbol = symbol',
  '  }',
  '',
  '  resourceName(): string {',
  "    return `sys.symbol.${this.name}`",
  '  }',
  '}',
  '',
  'export function createSystemSymbolCatalog(): SystemSymbolEntry[] {',
  '  return [',
]

for (const name of names) {
  lines.push(`    new SystemSymbolEntry('${name}', $r('sys.symbol.${name}')),`)
}
lines.push('  ]', '}', '')

const outputPath = join(
  repoRoot,
  'feature/settings/src/main/ets/generated/SystemSymbolCatalog.ets',
)
mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, lines.join('\n'))
console.log(`generated ${names.length} system symbols -> ${outputPath}`)
